package com.calendary.notifications.domain

enum class NotificationType {
	INVITATION_CREATED,
	INVITATION_ACCEPTED,
	BOOKING_REQUESTED,
	BOOKING_ACCEPTED,
	BOOKING_REJECTED,
	COLLABORATION_REQUESTED,
	COLLABORATION_ACCEPTED,
	COLLABORATION_REJECTED,
	RESOURCE_SHARED,
	RESOURCE_UPDATED,
}
